# Generated by Django 3.0 on 2024-11-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=25)),
                ('Place', models.CharField(max_length=25)),
                ('District', models.CharField(max_length=25)),
                ('Post', models.CharField(max_length=25)),
                ('Pin', models.IntegerField()),
                ('PhoneNumber', models.IntegerField()),
                ('Status', models.CharField(max_length=25)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Dob', models.DateField()),
                ('Place', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('Post', models.CharField(max_length=25)),
                ('Pin', models.IntegerField()),
                ('PhoneNumber', models.IntegerField()),
                ('Image', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=25)),
                ('Rating', models.CharField(max_length=25)),
                ('Date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Purpose', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('FileName', models.CharField(max_length=300)),
                ('Donations', models.CharField(max_length=50)),
                ('NeedDate', models.DateField()),
                ('Status', models.CharField(max_length=25)),
                ('ORGANIZER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Other', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.BigIntegerField()),
                ('Status', models.CharField(max_length=30)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=30)),
                ('Reply', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=30)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='ORGANIZER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Organizer'),
        ),
    ]
