# Generated by Django 3.0 on 2024-11-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20241106_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='Name',
        ),
    ]
